apiVersion: v1
kind: Secret
metadata:
  name: app-03-secret
  namespace: csharp-ten-apps
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=app03_db;Username=postgres;Password=change-me
  Jwt__Secret: change-me-32-char-secret
